const data = [
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat cupiditate esse unde officiis nemo repellat odit officia cum quisquam ullam tenetur consequuntur, vitae quia perspiciatis, odio in quae debitis mollitia! Laboriosam praesentium autem perferendis quam adipisci sint ratione deleniti numquam et ipsa perspiciatis tempora natus dicta maiores iure, nihil culpa.',
];

export default data;
